# Generated by Django 4.2.6 on 2023-10-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('id_project', models.IntegerField()),
                ('role', models.IntegerField()),
            ],
        ),
    ]
