# Generated by Django 4.2.6 on 2023-10-25 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0002_project_user_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_project',
            name='id_project',
        ),
        migrations.RemoveField(
            model_name='user_project',
            name='id_user',
        ),
        migrations.AddField(
            model_name='user_project',
            name='project',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='ide.project'),
        ),
        migrations.AddField(
            model_name='user_project',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='ide.user'),
        ),
    ]
