# Generated by Django 4.2.6 on 2023-10-25 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0003_remove_user_project_id_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_project',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ide.project'),
        ),
        migrations.AlterField(
            model_name='user_project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ide.user'),
        ),
    ]
